version: '3.8'
services:
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hola
      POSTGRES_DB: tfg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tfg
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: hola
    depends_on:
      - db

  frontend:
    build: ./frontend/frontendapp
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data: